### ISSUE TITLE
Fix notebooks documentation

### ISSUE THREAD

**Issue by gnzsnz** [ib-api-reloaded/ib_async#10]
All link on [notebooks](https://ib-api-reloaded.github.io/ib_async/notebooks.html) documentation are broken.

After checking the code i can see that all links point to `master` branch, which is the branch used by `ib_insync`, however this repo uses `main`

**Comment by nealeyoung** [comment]
Not sure if this is helpful, but here's corrected source for the page (just replaced "master" with "main" in the markdown):

------ SOURCE STARTS BELOW THIS LINE -----

.. _notebooks:

Notebooks
=========

IB-insync can be used in a fully interactive, exploratory way with live data from
within a `Jupyter <http://jupyter.org>`_ notebook.
Here are some recipe notebooks:

.. toctree::
   :maxdepth: 2

   Basics <https://nbviewer.jupyter.org/github/ib-api-reloaded/ib_async/tree/main/notebooks/basics.ipynb>
   Contract details <https://nbviewer.jupyter.org/github/ib-api-reloaded/ib_async/tree/main/notebooks/contract_details.ipynb>
   Option chain <https://nbviewer.jupyter.org/github/ib-api-reloaded/ib_async/tree/main/notebooks/option_chain.ipynb>
   Bar data <https://nbviewer.jupyter.org/github/ib-api-reloaded/ib_async/tree/main/notebooks/bar_data.ipynb>
   Tick data <https://nbviewer.jupyter.org/github/ib-api-reloaded/ib_async/tree/main/notebooks/tick_data.ipynb>
   Market depth <https://nbviewer.jupyter.org/github/ib-api-reloaded/ib_async/tree/main/notebooks/market_depth.ipynb>
   Ordering <https://nbviewer.jupyter.org/github/ib-api-reloaded/ib_async/tree/main/notebooks/ordering.ipynb>
   Scanners <https://nbviewer.jupyter.org/github/ib-api-reloaded/ib_async/tree/main/notebooks/scanners.ipynb>

**Comment by nealeyoung** [comment]
In the meantime, here are the correct links in a form easily usable by anyone who comes here looking for them:

   Basics <https://nbviewer.jupyter.org/github/ib-api-reloaded/ib_async/tree/main/notebooks/basics.ipynb>
   Contract details <https://nbviewer.jupyter.org/github/ib-api-reloaded/ib_async/tree/main/notebooks/contract_details.ipynb>
   Option chain <https://nbviewer.jupyter.org/github/ib-api-reloaded/ib_async/tree/main/notebooks/option_chain.ipynb>
   Bar data <https://nbviewer.jupyter.org/github/ib-api-reloaded/ib_async/tree/main/notebooks/bar_data.ipynb>
   Tick data <https://nbviewer.jupyter.org/github/ib-api-reloaded/ib_async/tree/main/notebooks/tick_data.ipynb>
   Market depth <https://nbviewer.jupyter.org/github/ib-api-reloaded/ib_async/tree/main/notebooks/market_depth.ipynb>
   Ordering <https://nbviewer.jupyter.org/github/ib-api-reloaded/ib_async/tree/main/notebooks/ordering.ipynb>
   Scanners <https://nbviewer.jupyter.org/github/ib-api-reloaded/ib_async/tree/main/notebooks/scanners.ipynb>

**Comment by mattsta** [comment]
Fixed via #11
