### ISSUE TITLE
Can't fetch reqHistoricalData

### ISSUE THREAD

**Issue by Amir-Inbar** [ib-api-reloaded/ib_async#49]
For some reason I can't fetch any historical data, I'm getting the same error again and again, what I'm doing wrong?.

Error:
`Error 200, reqId 8: No security definition has been found for the request, contract: Contract(secType='FUT', symbol='MES', lastTradeDateOrContractMonth='202409', exchange='GLOBEX', currency='USD')
`

`

    def fetch_market_data(self):
        contract = Contract(
            symbol="MES",
            secType="FUT",
            exchange="GLOBEX",
            currency="USD",
            lastTradeDateOrContractMonth="202409"
        )

        while True:
            try:
                bar_list = self._broker_agent.reqHistoricalData(
                    contract=contract,
                    endDateTime="",
                    durationStr="1 D",
                    barSizeSetting="1 hour",
                    whatToShow="TRADES",
                    useRTH=False,
                    formatDate=1,
                    keepUpToDate=True,
                )

                for bar in bar_list:
                    print(bar)
                self._broker_agent.sleep(10)
                self._logger.info(f"Received {len(bar_list)} bars.")
            except Exception as e:
                self._logger.error(f"Error fetching market data: {e}")
                raise e

`

Thanks!

**Comment by gnzsnz** [comment]
Your contract is wrong

Use this to get contract details

https://nbviewer.org/github/erdewit/ib_insync/blob/master/notebooks/contract_details.ipynb

Then select a valid expiration date and continue with your code


Regards,
Gonzalo Sáenz

**Comment by Amir-Inbar** [comment]
Works great, thanks!
