### ISSUE TITLE
is this a drop in of ib_insync?

### ISSUE THREAD

**Issue by disaster123** [ib-api-reloaded/ib_async#63]
Hi,

i don't find any migration hints. Can i just replace ib_insync with ib_async?

Thx!

Greets

**Comment by August1328** [comment]
yes, just replace the old module name with the new one.

same topic in [discussions ](https://github.com/ib-api-reloaded/ib_async/discussions/59)

**Comment by disaster123** [comment]
@August1328 to me this does not work.

I did:
```
git clone https://github.com/ib-api-reloaded/ib_async
```


```
import sys
sys.path.append(r'./ib_async/')

from ib_async import *
```

but this results in:
```
Traceback (most recent call last):
  File "/opt/metaibcopy/ib-client.py", line 11, in <module>
    import ibkr2
  File "/opt/metaibcopy/ibkr2.py", line 5, in <module>
    from ib_async import *
  File "./ib_async/ib_async/__init__.py", line 105, in <module>
    from .version import __version__, __version_info__
  File "./ib_async/ib_async/version.py", line 5, in <module>
    __version__ = version("ib_async")
  File "/usr/lib/python3.9/importlib/metadata.py", line 551, in version
    return distribution(distribution_name).version
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: ib_async

```

**Comment by August1328** [comment]
I am not familiar with every OS, but did you try `pip install ib_async`?

**Comment by disaster123** [comment]
OK the reason is the modfied version.py - the original one worked without any pip install. I've reverted to the old version.py ;-) works now. Thanks a lot!

**Comment by mattsta** [comment]
>   File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name

Yes, very much true. The minimum Python version is now 3.10 right now and it will continue to increase over time. Python 3.9 is almost 5 years old by now :(
